version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chat-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-app
    command: sh -c "sleep 7 && npm run dev"
    working_dir: /main
    environment:
      DOCKER: true
    volumes:
      - .:/main
      - /main/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: migrate
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "
      sleep 5;
      npx sequelize db:migrate --url postgres://postgres:postgres@postgres:5432/chatdb;
      "

volumes:
  pgdata: